# Generated by Django 3.0.4 on 2020-04-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200415_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tag',
            new_name='tags',
        ),
    ]
